### ISSUE TITLE
Make options pythonic

### ISSUE THREAD

**Issue by Mattwmaster58** [whtsky/pixelmatch-py#37]
Currently this library supports options in the form of a dictionary, however, this is quite unpythonic in my opinion and hinders the use of this library. I propose that you allow for **kwargs instead of requiring the passing in of a dictionary.

I'm willing to write a PR

**Comment by whtsky** [comment]
Yes, the options dict is not pythonic.

IMO, since we have a fixed number of options, listing every option instead of using **kwargs should 

* Have a better developer experience ( autocomplete & type hint in editor would be better ) 
* make the default values management easier

I'm happy to receive a PR for this if you have time.
